spring:
  application:
    name: gym-crm
  profiles:
    active: local
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
server:
  port: 8080

logging:
  pattern:
    level: "%5p [tx:%X{txId}]"
  level:
    org.hibernate.SQL: info
    org.springframework.web: info
