server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/gymcrm}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:A2b0r0a0m6a!}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.example.gymcrm: INFO
