spring:
  application:
    name: gym-crm
  profiles:
    active: local
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC

server:
  port: 8080

logging:
  pattern:
    level: "%5p [tx:%X{txId}]"
  level:
    org.hibernate.SQL: info
    org.springframework.web: info
    # Uncomment for verbose security debugging during setup:
    # org.springframework.security: debug

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true
      group:
        readiness:
          include:
            - db
            - users
            - trainingTypes
  metrics:
    tags:
      application: ${spring.application.name}

# --- Security / JWT / Brute-force ---
security:
  jwt:
    issuer: gym-crm
    secret: ${JWT_SECRET:change-me-in-dev}   # set JWT_SECRET in env for non-local
    ttl-minutes: 60
  brute-force:
    max-attempts: 3
    lock-minutes: 5

# --- CORS (used by SecurityConfig) ---
cors:
  allowed-origins: "*"
  allowed-methods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
  allowed-headers: "Authorization,Content-Type,X-Requested-With"
